name: Development workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: cd project2\drawing-app
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      # - name: Navigate to project directory
      #   run: cd /home/runner/work/project2/project2/drawing-app/package.json
      # - run: npm install
      # - run: npm run build
      # - name: Run tests
      #   run: npm test
      # - run: npm ci
      
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm test
