name: Development workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: ./
      - name: Use Node.js 17.x
        uses: ./
        with:
          node-version: 17.x
      # - name: Navigate to project directory
      #   run: cd /home/runner/work/project2/drawing-app/package.json
      - run: npm install
      - run: npm run build
      - name: Run tests
        run: npm test
